[browser]
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false

[theme]
# Primary accent color for interactive elements
primaryColor = "#F63366"

# Background color for the main content area
backgroundColor = "#FFFFFF"

# Background color used for the sidebar and most interactive widgets
secondaryBackgroundColor = "#F0F2F6"

# Color used for almost all text
textColor = "#262730"

# Font family for all text in the app, except code blocks
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = true

[server]
enableCORS = false
enableXsrfProtection = false

[logger]
level = "info"

[runner]
# These are your custom date and user settings
magicEnabled = true
postScriptGlobals = [
    "Current Date and Time (UTC): 2025-01-12 18:47:58",
    "Current User's Login: Bobosaad"
]

[mapbox]
token = ""
